name: CMake Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up build environment (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libprotobuf-dev protobuf-compiler cmake build-essential

      - name: Set up build environment (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          # Install vcpkg
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh -disableMetrics
          echo "VCPKG_ROOT=$(pwd)/vcpkg" >> $GITHUB_ENV

          # Install dependencies using vcpkg
          ./vcpkg/vcpkg install curl protobuf

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake (Windows)
        if: matrix.os == 'windows-latest'
        working-directory: ./build
        run: |
          cmake .. -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake

      - name: Configure CMake (Linux)
        if: matrix.os == 'ubuntu-latest'
        working-directory: ./build
        run: |
          cmake ..

      - name: Build project
        working-directory: ./build
        run: cmake --build . --config Release
